# Generated by Django 5.2.8 on 2025-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('wattage', models.PositiveIntegerField(blank=True, help_text='Power output in watts', null=True)),
                ('amp_type', models.CharField(blank=True, help_text='e.g., Tube, Solid-State, Hybrid, Modeling', max_length=100)),
                ('image1', models.URLField(blank=True, help_text='URL for first product image', max_length=500)),
                ('image2', models.URLField(blank=True, help_text='URL for second product image', max_length=500)),
                ('image3', models.URLField(blank=True, help_text='URL for third product image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amplifier',
                'verbose_name_plural': 'Amplifiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fuzz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('fuzz_type', models.CharField(blank=True, help_text='e.g., Germanium, Silicon, Hybrid', max_length=100)),
                ('image1', models.URLField(blank=True, help_text='URL for first product image', max_length=500)),
                ('image2', models.URLField(blank=True, help_text='URL for second product image', max_length=500)),
                ('image3', models.URLField(blank=True, help_text='URL for third product image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fuzzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('body_type', models.CharField(blank=True, help_text='e.g., Solid Body, Hollow Body, Semi-Hollow', max_length=100)),
                ('pickup_configuration', models.CharField(blank=True, help_text='e.g., SSS, HSS, HH, SS', max_length=50)),
                ('image1', models.URLField(blank=True, help_text='URL for first product image', max_length=500)),
                ('image2', models.URLField(blank=True, help_text='URL for second product image', max_length=500)),
                ('image3', models.URLField(blank=True, help_text='URL for third product image', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
