# Generated by Django 5.2.8 on 2024-12-02
# Data migration to populate Guitar, Amp, and Fuzz models with sample products

from django.db import migrations
from decimal import Decimal


def add_products(apps, schema_editor):
    """Add sample products to the database."""
    Guitar = apps.get_model('app', 'Guitar')
    Amp = apps.get_model('app', 'Amp')
    Fuzz = apps.get_model('app', 'Fuzz')

    # === GUITARS ===
    guitars_data = [
        # Stratocaster Series
        {
            'name': 'Guitar American Professional II Stratocaster',
            'brand': 'Fender',
            'price': Decimal('45000000.00'),
            'description': 'Đàn guitar Stratocaster cao cấp với pickup V-Mod II, cần đàn Deep C hiện đại và tremolo 2-Point Tremolo. Âm thanh sáng, trong trẻo, phù hợp cho Blues, Rock và Pop.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'SSS',
            'image1': 'https://images.unsplash.com/photo-1550291652-6ea9114a47b1?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar Player Stratocaster HSS',
            'brand': 'Fender',
            'price': Decimal('18500000.00'),
            'description': 'Stratocaster dòng Player với cấu hình HSS linh hoạt. Humbucker ở vị trí bridge cho âm thanh dày hơn, phù hợp cho Rock và Blues hiện đại.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'HSS',
            'image1': 'https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar Vintera 60s Stratocaster',
            'brand': 'Fender',
            'price': Decimal('32000000.00'),
            'description': 'Tái hiện âm thanh Strat vintage thập niên 60 với pickup 60s Modified Single-Coil. Cần đàn 60s "C" mềm mại, hoàn hảo cho nhạc Surf và Classic Rock.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'SSS',
            'image1': 'https://images.unsplash.com/photo-1525201548942-d8732f6617a0?w=600',
            'image2': '',
            'image3': '',
        },
        # Telecaster Series
        {
            'name': 'Guitar American Professional II Telecaster',
            'brand': 'Fender',
            'price': Decimal('42000000.00'),
            'description': 'Telecaster cao cấp với pickup V-Mod II cho âm thanh twang đặc trưng. Cần đàn Deep C thoải mái, phím đàn Super-Natural Satin finish.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'SS',
            'image1': 'https://images.unsplash.com/photo-1516924962500-2b4b3b99ea02?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar Player Telecaster',
            'brand': 'Fender',
            'price': Decimal('17500000.00'),
            'description': 'Telecaster dòng Player với âm thanh Tele cổ điển. Pickup Alnico 5 cho tone sáng và rõ ràng, lý tưởng cho Country, Indie và Alternative Rock.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'SS',
            'image1': 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar Deluxe Telecaster Thinline',
            'brand': 'Fender',
            'price': Decimal('28000000.00'),
            'description': 'Telecaster semi-hollow với âm thanh ấm áp, cộng hưởng tự nhiên. Wide Range humbucker cho tone dày và versatile.',
            'body_type': 'Semi-Hollow',
            'pickup_configuration': 'HH',
            'image1': 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=600',
            'image2': '',
            'image3': '',
        },
        # Gibson / Les Paul Series
        {
            'name': 'Guitar Les Paul Standard 50s',
            'brand': 'Gibson',
            'price': Decimal('65000000.00'),
            'description': 'Les Paul Standard với tái hiện chính xác specs thập niên 50. Burstbucker pickups cho tone vintage ấm áp, thân đàn Mahogany với top Maple AA Figure.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'HH',
            'image1': 'https://images.unsplash.com/photo-1508186225823-0963cf9ab0de?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar Les Paul Studio',
            'brand': 'Gibson',
            'price': Decimal('42000000.00'),
            'description': 'Les Paul Studio - âm thanh Les Paul đích thực với giá thành hợp lý. 490R/498T pickups cho tone đa dạng từ Blues đến Hard Rock.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'HH',
            'image1': 'https://images.unsplash.com/photo-1558098329-a11cff621064?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Guitar SG Standard',
            'brand': 'Gibson',
            'price': Decimal('48000000.00'),
            'description': 'SG Standard với thân đàn nhẹ, cần đàn SlimTaper dễ chơi. 490R/490T pickups cho âm thanh Rock mạnh mẽ, đặc trưng của AC/DC.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'HH',
            'image1': 'https://images.unsplash.com/photo-1605020420620-20c943cc4669?w=600',
            'image2': '',
            'image3': '',
        },
        # User requested: Mocking Bird
        {
            'name': 'Guitar Mockingbird Extreme',
            'brand': 'B.C. Rich',
            'price': Decimal('35000000.00'),
            'description': 'Đàn guitar Mockingbird huyền thoại với thiết kế aggressive độc đáo. Dual humbucker cho tone Metal và Hard Rock cực mạnh, cần đàn nhanh phù hợp cho shred và sweep picking.',
            'body_type': 'Solid Body',
            'pickup_configuration': 'HH',
            'image1': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600',
            'image2': '',
            'image3': '',
        },
    ]

    for guitar_data in guitars_data:
        Guitar.objects.create(**guitar_data)

    # === AMPLIFIERS ===
    amps_data = [
        # User requested: Marshall JCM 800
        {
            'name': 'Amplifier JCM800 2203X',
            'brand': 'Marshall',
            'price': Decimal('75000000.00'),
            'description': 'Huyền thoại Marshall JCM 800 tái bản chính hãng. Công suất 100W đèn điện tử, âm thanh Rock/Metal kinh điển từ thập niên 80. Được sử dụng bởi Slash, Zakk Wylde và hàng nghìn guitar hero.',
            'wattage': 100,
            'amp_type': 'Tube',
            'image1': 'https://images.unsplash.com/photo-1619558041949-8c8481de6d73?w=600',
            'image2': '',
            'image3': '',
        },
        # Tube Amps
        {
            'name': 'Amplifier AC30S1',
            'brand': 'Vox',
            'price': Decimal('45000000.00'),
            'description': 'Ampli đèn Vox AC30 với âm thanh British chime đặc trưng. 30W công suất, tremolo và reverb tích hợp. Hoàn hảo cho Beatles, Radiohead style.',
            'wattage': 30,
            'amp_type': 'Tube',
            'image1': 'https://images.unsplash.com/photo-1558584673-ee04eaa32560?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier Blues Junior IV',
            'brand': 'Fender',
            'price': Decimal('22000000.00'),
            'description': 'Ampli đèn 15W nhỏ gọn, âm thanh Fender clean ấm áp. Spring reverb cổ điển, phù hợp cho phòng tập và gig nhỏ.',
            'wattage': 15,
            'amp_type': 'Tube',
            'image1': 'https://images.unsplash.com/photo-1535587566541-97121a128dc5?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier Dual Rectifier',
            'brand': 'Mesa Boogie',
            'price': Decimal('85000000.00'),
            'description': 'Ampli đèn 100W huyền thoại cho Metal và Hard Rock. 3 channel độc lập, gain cao, âm thanh heavy đặc trưng.',
            'wattage': 100,
            'amp_type': 'Tube',
            'image1': 'https://images.unsplash.com/photo-1485579149621-3123dd979885?w=600',
            'image2': '',
            'image3': '',
        },
        # Practice Amps
        {
            'name': 'Amplifier Katana-50 MkII',
            'brand': 'Boss',
            'price': Decimal('8500000.00'),
            'description': 'Ampli combo 50W với công nghệ Tube Logic. 5 amp type, 60+ hiệu ứng BOSS, kết nối Bluetooth và USB recording.',
            'wattage': 50,
            'amp_type': 'Practice',
            'image1': 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier THR10II',
            'brand': 'Yamaha',
            'price': Decimal('9500000.00'),
            'description': 'Ampli desktop 20W với thiết kế đẹp mắt. VCM công nghệ mô phỏng ampli analog, hiệu ứng chất lượng cao, loa stereo.',
            'wattage': 20,
            'amp_type': 'Practice',
            'image1': 'https://images.unsplash.com/photo-1571974599782-8d1ade3b7e18?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier Spark 40',
            'brand': 'Positive Grid',
            'price': Decimal('7500000.00'),
            'description': 'Ampli thông minh 40W với AI Jam tự động đệm nhạc. 10,000+ preset từ cộng đồng, Bluetooth streaming và app điều khiển.',
            'wattage': 40,
            'amp_type': 'Practice',
            'image1': 'https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=600',
            'image2': '',
            'image3': '',
        },
        # Solid State Amps
        {
            'name': 'Amplifier JC-40',
            'brand': 'Roland',
            'price': Decimal('18000000.00'),
            'description': 'Jazz Chorus 40W với âm clean trong vắt huyền thoại. Stereo chorus effect đặc trưng, 2x10" speakers.',
            'wattage': 40,
            'amp_type': 'Solid State',
            'image1': 'https://images.unsplash.com/photo-1508186225823-0963cf9ab0de?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier Bandit 112',
            'brand': 'Peavey',
            'price': Decimal('12000000.00'),
            'description': 'Ampli solid-state 80W bền bỉ, giá thành hợp lý. TransTube công nghệ cho âm thanh gần tube amp.',
            'wattage': 80,
            'amp_type': 'Solid State',
            'image1': 'https://images.unsplash.com/photo-1565073624497-7144969d0a07?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Amplifier Nextone Stage',
            'brand': 'Boss',
            'price': Decimal('25000000.00'),
            'description': 'Ampli 40W với công nghệ Tube Logic mô phỏng 4 loại power tube. Kết nối GA-FC footswitch, Air Feel cho cảm giác như ampli đèn.',
            'wattage': 40,
            'amp_type': 'Solid State',
            'image1': 'https://images.unsplash.com/photo-1558584673-ee04eaa32560?w=600',
            'image2': '',
            'image3': '',
        },
    ]

    for amp_data in amps_data:
        Amp.objects.create(**amp_data)

    # === FUZZ PEDALS ===
    fuzzes_data = [
        # Analog Fuzz
        {
            'name': 'Fuzz Big Muff Pi',
            'brand': 'Electro-Harmonix',
            'price': Decimal('2800000.00'),
            'description': 'Fuzz pedal huyền thoại với âm sustain dày, mạnh mẽ. Sử dụng bởi Jimi Hendrix, David Gilmour. Tone và Sustain controls.',
            'fuzz_type': 'Analog',
            'image1': 'https://images.unsplash.com/photo-1629483217432-e8be6c65a83f?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Face Mini Germanium',
            'brand': 'Dunlop',
            'price': Decimal('4500000.00'),
            'description': 'Fuzz Face với linh kiện Germanium cho âm thanh vintage ấm áp. Thiết kế compact, true bypass, 9V adapter.',
            'fuzz_type': 'Analog',
            'image1': 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Hoof',
            'brand': 'EarthQuaker Devices',
            'price': Decimal('5500000.00'),
            'description': 'Fuzz germanium/silicon hybrid với shift control độc đáo. Từ fuzz nhẹ đến doom metal crushing. Handmade in USA.',
            'fuzz_type': 'Analog',
            'image1': 'https://images.unsplash.com/photo-1558584673-ee04eaa32560?w=600',
            'image2': '',
            'image3': '',
        },
        # Digital Fuzz
        {
            'name': 'Fuzz MultiStomp MS-70CDR',
            'brand': 'Zoom',
            'price': Decimal('3500000.00'),
            'description': 'Multi-effect digital với 86 chorus/delay/reverb + fuzz effects. Nhỏ gọn, chạy pin, USB editor. Chất lượng studio.',
            'fuzz_type': 'Digital',
            'image1': 'https://images.unsplash.com/photo-1551969014-7d2c4cddf0b6?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Plasma Pedal',
            'brand': 'Gamechanger Audio',
            'price': Decimal('8500000.00'),
            'description': 'Fuzz digital độc đáo sử dụng xenon tube. Âm thanh aggressive, voltage-controlled distortion, LED hiển thị plasma thực.',
            'fuzz_type': 'Digital',
            'image1': 'https://images.unsplash.com/photo-1619558041949-8c8481de6d73?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Source Audio Aftershock',
            'brand': 'Source Audio',
            'price': Decimal('6500000.00'),
            'description': 'Fuzz/distortion digital với 24 engines, MIDI control, stereo I/O. Neuro app editor, preset save, expression pedal input.',
            'fuzz_type': 'Digital',
            'image1': 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600',
            'image2': '',
            'image3': '',
        },
        # Enclosure Fuzz (Boutique / Custom pedals)
        {
            'name': 'Fuzz Factory',
            'brand': 'ZVex',
            'price': Decimal('7000000.00'),
            'description': 'Fuzz boutique với 5 controls cho oscillating fuzz chaos. Hand-painted enclosure, handwired circuit. Từ vintage fuzz đến noise machine.',
            'fuzz_type': 'Enclosure',
            'image1': 'https://images.unsplash.com/photo-1629483217432-e8be6c65a83f?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Model feT',
            'brand': 'Fairfield Circuitry',
            'price': Decimal('6000000.00'),
            'description': 'Fuzz/drive boutique với gain range rộng. Compact enclosure aluminum cao cấp, handmade in Canada. Clean boost đến woolly fuzz.',
            'fuzz_type': 'Enclosure',
            'image1': 'https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Pharaoh Supreme',
            'brand': 'Black Arts Toneworks',
            'price': Decimal('5800000.00'),
            'description': 'Fuzz/doom pedal với high gain và massive sustain. Enclosure chất lượng cao, true bypass, germanium diodes option.',
            'fuzz_type': 'Enclosure',
            'image1': 'https://images.unsplash.com/photo-1558584673-ee04eaa32560?w=600',
            'image2': '',
            'image3': '',
        },
        # Multi-Effect
        {
            'name': 'Fuzz GT-1000',
            'brand': 'Boss',
            'price': Decimal('22000000.00'),
            'description': 'Multi-effect flagship với AIRD công nghệ. 116 effects, stereo I/O, Bluetooth editor, USB audio interface. Tour-ready quality.',
            'fuzz_type': 'Multi Effect',
            'image1': 'https://images.unsplash.com/photo-1551969014-7d2c4cddf0b6?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz Helix Floor',
            'brand': 'Line 6',
            'price': Decimal('38000000.00'),
            'description': 'Multi-effect cao cấp với amp/cab modeling chất lượng studio. Touchscreen, expression pedals, XLR outputs. Giải pháp all-in-one.',
            'fuzz_type': 'Multi Effect',
            'image1': 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600',
            'image2': '',
            'image3': '',
        },
        {
            'name': 'Fuzz HX Stomp',
            'brand': 'Line 6',
            'price': Decimal('18500000.00'),
            'description': 'Helix nhỏ gọn trong enclosure compact. 300+ effects, amp/cab models, stereo I/O. USB audio, MIDI, expression input.',
            'fuzz_type': 'Multi Effect',
            'image1': 'https://images.unsplash.com/photo-1619558041949-8c8481de6d73?w=600',
            'image2': '',
            'image3': '',
        },
    ]

    for fuzz_data in fuzzes_data:
        Fuzz.objects.create(**fuzz_data)


def remove_products(apps, schema_editor):
    """Remove the sample products (for rollback)."""
    Guitar = apps.get_model('app', 'Guitar')
    Amp = apps.get_model('app', 'Amp')
    Fuzz = apps.get_model('app', 'Fuzz')
    
    # Remove products by name (to avoid deleting user-added products)
    guitar_names = [
        'Guitar American Professional II Stratocaster',
        'Guitar Player Stratocaster HSS',
        'Guitar Vintera 60s Stratocaster',
        'Guitar American Professional II Telecaster',
        'Guitar Player Telecaster',
        'Guitar Deluxe Telecaster Thinline',
        'Guitar Les Paul Standard 50s',
        'Guitar Les Paul Studio',
        'Guitar SG Standard',
        'Guitar Mockingbird Extreme',
    ]
    Guitar.objects.filter(name__in=guitar_names).delete()
    
    amp_names = [
        'Amplifier JCM800 2203X',
        'Amplifier AC30S1',
        'Amplifier Blues Junior IV',
        'Amplifier Dual Rectifier',
        'Amplifier Katana-50 MkII',
        'Amplifier THR10II',
        'Amplifier Spark 40',
        'Amplifier JC-40',
        'Amplifier Bandit 112',
        'Amplifier Nextone Stage',
    ]
    Amp.objects.filter(name__in=amp_names).delete()
    
    fuzz_names = [
        'Fuzz Big Muff Pi',
        'Fuzz Face Mini Germanium',
        'Fuzz Hoof',
        'Fuzz MultiStomp MS-70CDR',
        'Fuzz Plasma Pedal',
        'Fuzz Source Audio Aftershock',
        'Fuzz Factory',
        'Fuzz Model feT',
        'Fuzz Pharaoh Supreme',
        'Fuzz GT-1000',
        'Fuzz Helix Floor',
        'Fuzz HX Stomp',
    ]
    Fuzz.objects.filter(name__in=fuzz_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_amp_price_alter_fuzz_price_alter_guitar_price'),
    ]

    operations = [
        migrations.RunPython(add_products, remove_products),
    ]
